### PR TITLE
Performs generic maintainance, dependencies version bumping and brings in dark theme support 

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by ptoscano** [comment]
Hi @KKoukiou,

thanks for the updates! It was definitely due time for this. I'll try to take a look -- cannot promise anything soon though :/

One thing I know and I can mention is regarding the newer API of `cockpit.Dialog` & `cockpit.DialogFooter`, see commit f87a389d9d528197c26e8a8afbae2ede47815dc5 for a longer explanation. IMHO a good change here could be to switch the title to something short & generic, and to add the longer error details as content, according to what https://github.com/cockpit-project/cockpit/commit/94b1dbbd794fccac48b66018363209a2ee4b161c.

**Comment by KKoukiou** [comment]
> Hi @KKoukiou,
> 
> thanks for the updates! It was definitely due time for this. I'll try to take a look -- cannot promise anything soon though :/
> 
> One thing I know and I can mention is regarding the newer API of `cockpit.Dialog` & `cockpit.DialogFooter`, see commit [f87a389](https://github.com/candlepin/subscription-manager-cockpit/commit/f87a389d9d528197c26e8a8afbae2ede47815dc5) for a longer explanation. IMHO a good change here could be to switch the title to something short & generic, and to add the longer error details as content, according to what [cockpit-project/cockpit@94b1dbb](https://github.com/cockpit-project/cockpit/commit/94b1dbbd794fccac48b66018363209a2ee4b161c).

We can review the titles and of the error messages of this plugin definitely, but why you want this to be part of this PR? I just make the necessary changes here for picking up the newest lib.

**Comment by ptoscano** [comment]
> why you want this to be part of this PR? I just make the necessary changes here for picking up the newest lib.

I thought that it would somehow change the behaviour, especially since the version bump of the cockpit library is a step forward 16 months (!). If there is no behaviour change, that's OK to be done afterwards then.

**Comment by KKoukiou** [comment]
> > why you want this to be part of this PR? I just make the necessary changes here for picking up the newest lib.
> 
> I thought that it would somehow change the behaviour, especially since the version bump of the cockpit library is a step forward 16 months (!). If there is no behaviour change, that's OK to be done afterwards then.

The behavior change (which required these few test adjustments) is that the errors in modals are moved from the footer into the dialog body. In specific this commit https://github.com/cockpit-project/cockpit/commit/9d90a4b1c6a3d92b93897e6a75313d2449ff8d25

**Comment by ptoscano** [comment]
> > > why you want this to be part of this PR? I just make the necessary changes here for picking up the newest lib.
> > 
> > 
> > I thought that it would somehow change the behaviour, especially since the version bump of the cockpit library is a step forward 16 months (!). If there is no behaviour change, that's OK to be done afterwards then.
> 
> The behavior change (which required these few test adjustments) is that the errors in modals are moved from the footer into the dialog body. In specific this commit [cockpit-project/cockpit@9d90a4b](https://github.com/cockpit-project/cockpit/commit/9d90a4b1c6a3d92b93897e6a75313d2449ff8d25)

OK, no problem then.

(and yay for things written days ago, and never sent as intended...)

**Comment by ptoscano** [comment]
Sorry for the delay. I gave it some testing, and it seems to work fine, as expected, no changes I was able to see.

Can you please rebase it one more time, as Martin's fix was merged in the meanwhile?

Thanks!

**Pull request merged**
