### PR TITLE
test: Sync packagelib.py with cockpit main

### PR DESCRIPTION
**Pull request by martinpitt**
Sync with cockpit 97e0a7d7a11bc6.
    
This will prepare the tests for changing Machine.execute() to run with
`set -e` by default. See https://github.com/cockpit-project/cockpit/pull/17624

---

Fixes [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3706-20220808-044716-9d7a8a86-fedora-36-candlepin-subscription-manager-cockpit/log.html).

 - Blocked on https://github.com/cockpit-project/cockpit/pull/17624

### CODE REVIEW

**Comment by ptoscano** [comment]
Please note that this file (`packagelib.py`) is copied from cockpit:
https://github.com/cockpit-project/cockpit/blob/main/test/verify/packagelib.py
Hmm I do not see any PR that changes that file as well; am I missing anything?

Also, considering that:
- the test API was recently bumped (#32)
- there was a fix for a regression in the test lib for non-parallel tests (https://github.com/cockpit-project/cockpit/pull/17603)
- I think it would be better to have `packagelib.py` coming from the same version of the cockpit test lib (simulating it was part of it, kinda)

then what I would do is:
- do this fix in cockpit.git
- bump the test API to a commit that the includes the fix, with an extra commit (ala cc4e3470a838ed8e093443128f9d0aff846bee2f)  to sync `packagelib.py` from cockpit

What do you think?

**Comment by martinpitt** [comment]
Right, I'm going to fix this in cockpit as well. I'm trawling through the failures in the bots PR, and sub-man was just the first to fail :grin:  Moving to draft and blocking on that.

**Comment by martinpitt** [comment]
... at least I have some green test results to prove that nothing else needs changing, so that wasn't completely in vain :grin:

**Comment by martinpitt** [comment]
@ptoscano : Better? PTAL!

**Comment by martinpitt** [comment]
@ptoscano : BTW, my next plan is to move test/verify/packagelibpy to just test, and directly pull it in via git. I have another commit queued up for that, but that needs a change in cockpit first. Then the code copy will be gone entirely.

**Comment by ptoscano** [comment]
> my next plan is to move test/verify/packagelib.py to just test/

ITYM `test/common/`? If so, that'd be awesome!

**Review by ptoscano — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
