### PR TITLE
Update cockpit test lib and webpack build to fix tests with Chromium 113

### PR DESCRIPTION
**Pull request by martinpitt**
The most recent Chromium 113 does not work any more with sizzle, tests were hanging as soon as they switched to a frame. The latest cockpit testlib applied a workaround [1], pull that in.

Due to the conversion from CommonJS to ESM, this requires updating Cockpit's pkg/lib as well. Update the webpack NPM modules and configuration to the most recent starter-kit version (commit 0aaccb9ea1, right before the conversion to esbuild):

 * Use ESM `import` instead of `require()`.

 * This actually *uses* terser and CSS minifier to reduce the webpack size, instead of just importing it in vain.

 * Drop the unused and unsupportable srcdir/builddir variables for building in a separate directory.

 * Don't compress CSS in devel mode.

 * Drop the obsolete md4 hack.

[1] https://github.com/cockpit-project/cockpit/pull/18812

### CODE REVIEW

**Comment by martinpitt** [comment]
Meh, this is [too far apart](https://cockpit-logs.us-east-1.linodeobjects.com/pull-58-20230517-054603-668ac5e3-centos-9-stream/log.html) . It at least needs the conversion to a module, and who knows what else. So this is going to be a bigger change.

**Comment by martinpitt** [comment]
@ptoscano : This is sort of urgent, as Chromium 113 is already in all stable Fedora versions. Can you please review this? Grazie mille!

**Comment by martinpitt** [comment]
@ptoscano Friendly ping? I'm happy to explain any changes here. I realize it's a rather big commit, but that's more practical than trying to hunt down and backport dozens of individual webpack/esbuild commits. For the most part this is "keep the build system in sync with projects" and "it compiles, it tests, it works" :grin: Thanks!

**Comment by martinpitt** [comment]
Friendly ping?

**Comment by martinpitt** [comment]
Weekly ping. We have to update our tasks container soon now, as we need to make some updates and test with current browsers. At that point sub-man will break and we'll take it out of the test map until this lands.

**Review by jirihnidek — APPROVED** [review]
LGTM :+1: Thanks

**Pull request merged**
